### ISSUE TITLE
[Bug]: invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by lictw** [project-zot/zot#1703] opened 2023-08-14 21:18 UTC
### zot version

2.0.0-rc6

### Describe the bug

```
{"level":"error","errorType":"*json.SyntaxError","blobURL":"https://docker.io/v2/","error":"invalid character '<' looking for beginning of value","goroutine":37,"caller":"zotregistry.io/zot/pkg/common/http_client.go:161","time":"2023-08-15T00:14:22.535140032+03:00","message":"couldn't unmarshal remote blob"}
```
zot's spaming with this error.

### To reproduce

```
{
          "urls": ["https://docker.io"],
          "onDemand": true,
          "content": [{"prefix": "**", "destination": "docker.io"}]
}
```
configuration block

**Comment by rchincha** [comment] 2023-08-15 01:33
@lictw Thanks for trying out zot.

https://github.com/project-zot/zot/blob/main/examples/config-popular-registries.json#L20
https://github.com/project-zot/zot/blob/main/examples/config-popular-registries.json

^ would refer to this. Let us know if it still doesn't work.

**Comment by lictw** [comment] 2023-08-15 02:42
The same, but mirror works, even without *library*, just an error in all cases.

**Comment by rchincha** [comment] 2023-08-15 16:03
@lictw is the sync feature working for you at all?

@peusebiu is this because we hit rate-limiting messages instead of the actual blob?

**Comment by rchincha** [comment] 2023-08-15 17:52
@lictw Would it be possible for you to build and test a custom zot binary with the following instrumentation.
https://github.com/project-zot/zot/blob/main/pkg/common/http_client.go#L160

.Str("body", string(body)) 

... so we get a better idea of what the issue is. It looks like some HTML is being emitted.

**Comment by rchincha** [comment] 2023-08-16 17:00
@peusebiu another thing to check is some images may be public that can be sync'ed but others not (I don't see creds in the config) so they will fail.

**Comment by peusebiu** [comment] 2023-08-17 10:32
Hello, this is part of zot sync pinging registries (found in 'urls' config option) before selecting one, it tries to ping /v2/ route but /v2/ is not a valid route for all registries. 

Even if the ping fails it will still try to use one url from config option, so it's just spamming, I will try to come up with a fix for this.

**Comment by lictw** [comment] 2023-08-17 15:46
> others not (I don't see creds in the config)

ZOT spams errors even if nothing are downloading through the proxy, just after the block added.

Am I right that you obtain the source of problem? @peusebiu 

<sub>Also @rchincha, sorry for off-topping here: answer me to [this question](https://github.com/project-zot/zot/discussions/1587#discussioncomment-6727040), please!</sub>

**Comment by peusebiu** [comment] 2023-08-17 16:12
Yes @lictw I'll fix it. Thank you!

**Closed** 2023-09-13 17:00 UTC
Labels: bug, rm-external
