### ISSUE TITLE
[Feat]: smaller binary / import cost

### ISSUE THREAD

**Issue by smoser** [project-zot/zot#1677] opened 2023-08-03 20:26 UTC
### Is your feature request related to a problem? Please describe.

The difference in size for zot from 1.4.3 and current master branch is substantial.   I'm wondering if there is any low hanging of imports to drop that could reduce the size of zot back closer to the 1.4.3. size.

| asset                   |  1.4.3   | 2.0.0-rc6 |
| --                      |  --      | --        |
| zot-linux-amd64         |  63.9 MB | 133 MB    |
| zot-linux-amd64-minimal |  34.9 MB |  63.7 MB  |

Note that I've recorded sizes of the binaries, but the size inflation is incurred by any user of a golang import. A project that i'm working on was trying to start its own zot servier via go import of zotregistry.io/zot/pkg/api and use api.NewController, and ctrl.Init/ctrl.Run.  The use increased my executable by ~60M.

I'm attaching a 'importzot' git repo here that you can build for yourself.  It builds with effectively the "minimal" zot build flags.
[importzot.tar.gz](https://github.com/project-zot/zot/files/12254723/importzot.tar.gz)

The 1.4.3 binary is 32M.
The 2.0 binary is 65M.

just for easy view, here is the 'import-zot.go' source:

```go
package main

import (
	"context"

	"zotregistry.io/zot/pkg/api"
	"zotregistry.io/zot/pkg/api/config"
)

func main() {
	cfg := config.New()
	ctx := context.Background()
	ctrl := api.NewController(cfg)

        // (not used against v1.4 as it doesn't have ctrl.Init)
	if err := ctrl.Init(ctx); err != nil {
		panic(err)
	}

	if err := ctrl.Run(ctx); err != nil {
		panic(err)
	}
}
```

One thing to note is the call to ctrl.Init  costs 10M (without it, the binary is 55M).

**Comment by rchincha** [comment] 2023-08-04 00:56
Duplicate of issue #1412

**Comment by smoser** [comment] 2023-08-04 14:29
> Duplicate of issue #1412

close this ?

**Comment by andaaron** [comment] 2023-08-07 07:38
Closing as duplicate.

**Closed** 2023-08-07 07:39 UTC
Labels: feature
